<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderDetailTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('orderdetail')->insert([
            [
                'code'=>'AS',
                'price'=>'5000',
                'quantity'=>'5',
                'image'=>'ao.jpg',
                'ord_id'=>'1'
            ],
            [
                'code'=>'AM',
                'price'=>'6000',
                'quantity'=>'2',
                'image'=>'aomi.jpg',
                'ord_id'=>'1'
            ],
            [
                'code'=>'QA',
                'price'=>'6000',
                'quantity'=>'1',
                'image'=>'quanau.jpg',
                'ord_id'=>'1'
            ],
            [
                'code'=>'QA',
                'price'=>'7000',
                'quantity'=>'9',
                'image'=>'aoquan.jpg',
                'ord_id'=>'1'
            ],
            [
                'code'=>'AS',
                'price'=>'5000',
                'quantity'=>'5',
                'image'=>'ao.jpg',
                'ord_id'=>'2'
            ],
            [
                'code'=>'AM',
                'price'=>'6000',
                'quantity'=>'2',
                'image'=>'aomi.jpg',
                'ord_id'=>'2'
            ],
            [
                'code'=>'QA',
                'price'=>'6000',
                'quantity'=>'1',
                'image'=>'quanau.jpg',
                'ord_id'=>'2'
            ],
            [
                'code'=>'QA',
                'price'=>'7000',
                'quantity'=>'9',
                'image'=>'aoquan.jpg',
                'ord_id'=>'2'
            ],
            [
                'code'=>'AS',
                'price'=>'5000',
                'quantity'=>'5',
                'image'=>'ao.jpg',
                'ord_id'=>'3'
            ],
            [
                'code'=>'AM',
                'price'=>'6000',
                'quantity'=>'2',
                'image'=>'aomi.jpg',
                'ord_id'=>'3'
            ],
            [
                'code'=>'QA',
                'price'=>'6000',
                'quantity'=>'1',
                'image'=>'quanau.jpg',
                'ord_id'=>'3'
            ],
            [
                'code'=>'QA',
                'price'=>'7000',
                'quantity'=>'9',
                'image'=>'aoquan.jpg',
                'ord_id'=>'4'
            ],
        ]);
    }
}